"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var myName = "Shubham";
var myAge = 25;
var isDeveloper = true;
var score = [81, 86, 75];
var hobbies = ['coding', 'gaming'];
var biodata = [myName, myAge];
console.log('myName:', myName);
console.log('myAge:', myAge);
console.log('isDeveloper:', isDeveloper);
console.log('score:', score);
console.log('hobbies:', hobbies);
console.log('biodata:', biodata);
var randomType = "hello";
console.log('randomType:', randomType);
randomType = 123;
console.log('randomType:', randomType);
randomType = true;
console.log('randomType:', randomType);
// Assigning multiple types to a variable or say Union types
var value;
value = "Hello";
console.log("value: ".concat(value));
value = 24;
console.log("value: ".concat(value));
// any type
var data = "Hello";
data = 123;
console.log("data: ".concat(data));
data = true;
console.log("data: ".concat(data));
